### PR TITLE
Added lowercase functions and tests.

### PR DESCRIPTION
**Pull request by Wineh**

### CODE REVIEW

**Comment by zyronix** [comment]
Awesome, love this feature! Could you do two more things?
- Bump version number
- add docs for the feature

**Review by zyronix — CHANGES_REQUESTED** [review]
See commit above

**Comment by Wineh** [comment]
> Awesome, love this feature! Could you do two more things?
> 
>     * Bump version number
> 
>     * add docs for the feature

Done!

**Comment by Wineh** [comment]
> Awesome, love this feature! Could you do two more things?
> 
>     * Bump version number
> 
>     * add docs for the feature

Done!

**Review by zyronix — APPROVED** [review]

**Pull request merged**
