### PR TITLE
Allow demeuking entire (nested) directories using glob expressions

### PR DESCRIPTION
**Pull request by bartbroere**
When demeuking the BreachCompilation dataset, I noticed the restriction that demeuk by default processes only one file.

Using `glob`, processing entire directories would be possible, with patterns like:

```demeuk -i ./BreachCompilation/*/* -o demeuked_breachcompilation.dict```
or 
```demeuk -i ./BreachCompilation/** -o demeuked_breachcompilation.dict```

That seemed like a quick win to me. It doesn't break any existing behaviour. <sup>[citation needed]</sup>

If this is considered for a merge, I am willing to 
+ document it
+ add some tests
+ add logging output about the number of matching files so the user gets feedback on the results of the glob expression

(hence the work-in-progress label)

If it's not considered, no hard feelings either, but I will not do the busywork of documenting it and writing tests.

### CODE REVIEW

**Comment by bartbroere** [comment]
Ah, I just read the part of the documentation where it says merging files could be done with Unix tools.

> The first step you have to document is combine the datafiles into one single file. Using default Linux tooling for this works very well. 

I still think the solution in this pull request can save everyone some unneccessary I/O operations though.

**Comment by zyronix** [comment]
Awesome improvement! I guess you didn't test the code yet? Because running this on a dir with multiple files results in an error. I have continued the implementation a bit.

The chunkify function should also yield the filename

```
@@ -743,7 +745,7 @@ def chunkify(fname, size=1024 * 1024):
                 f.seek(size, 1)
                 f.readline()
                 chunkend = f.tell()
-                yield chunkstart, chunkend - chunkstart
+                yield chunkstart, chunkend - chunkstart, filename
                 if chunkend > fileend:
                     break
```

This should be returned to the jobs queue
```
@@ -928,8 +930,8 @@ def main():
     jobs = []
 
     print('Main: starting chunking file.')
-    for chunk_start, chunk_size in chunkify(input_file):
-        jobs.append(pool.apply_async(clean_up, (input_file, chunk_start, chunk_size, config)))
+    for chunk_start, chunk_size, filename in chunkify(input_file):
+        jobs.append(pool.apply_async(clean_up, (filename, chunk_start, chunk_size, config)))
     print('Main: done chunking file.')
 
     print('Main: starting threads.')
```

Then the main clean_up function should write temp results for each chunk to a new temp file. I though hashing the filename with md5 would return in a unique enough ID for temp files. If you have different ideas for this please let me know.

```
@@ -76,6 +76,7 @@
 
 from binascii import hexlify, unhexlify
 from glob import glob
+from hashlib import md5
 from html import unescape
 from inspect import cleandoc
 from locale import LC_ALL, setlocale

@@ -544,6 +545,7 @@ def clean_up(filename, chunk_start, chunk_size, config):
     log = []
 
     temp_folder = 'demeuk_tmp'
+    temp_file = md5(filename.encode()).hexdigest()
 
     with open(filename, 'rb') as f:
         f.seek(chunk_start)
@@ -714,19 +716,19 @@ def clean_up(filename, chunk_start, chunk_size, config):
 
         # We made it all the way here, check if we need to flush lines to disk
         if len(log) > 10000 or len(results) > 10000:
-            with open(path.join(temp_folder, f'{chunk_start}_result.txt'), 'a') as f:
+            with open(path.join(temp_folder, f'{temp_file}_{chunk_start}_result.txt'), 'a') as f:
                 f.write(''.join(results))
             # Make sure list is deleted from memory
             del results[:]
-            with open(path.join(temp_folder, f'{chunk_start}_log.txt'), 'a') as f:
+            with open(path.join(temp_folder, f'{temp_file}_{chunk_start}_log.txt'), 'a') as f:
                 f.write(''.join(log))
             # Make sure list is deleted from memory
             del log[:]
 
     # Processed all lines, flush everything
-    with open(path.join(temp_folder, f'{chunk_start}_result.txt'), 'a') as f:
+    with open(path.join(temp_folder, f'{temp_file}_{chunk_start}_result.txt'), 'a') as f:
         f.write(''.join(results))
-    with open(path.join(temp_folder, f'{chunk_start}_log.txt'), 'a') as f:
+    with open(path.join(temp_folder, f'{temp_file}_{chunk_start}_log.txt'), 'a') as f:
         f.write(''.join(log))
```

I could submit the code above in a PR to your code, but what is the fun in that right? Happy copying and pasting ;)

Regarding performance and this feature.
I tried to implement recursive file before, however it seem to slow down the whole process. Especially on machines with lot of CPU cores. To verify if your code had the same problems I ran it onto some dirty data shattered over multiple directories. Interestingly the performance was roughly the same:

1 minute 38.7s for data concatted
1 minute 40s for the recursive glob implementation.

So your idea to use glob looks awesome!

Also did a linecount on the files. They were the same. Only note: the order of content in the files are different. Which makes sense to be honest. I sorted both files and the output of the files were identical in the end.

In the end, thanks a lot for this idea. Are you willing to finalize the code? Please paste my code changes in your pull request. Update the docs with some examples and write a test proving that the code does was it supposed to do.

Note that if you are running demeuk on some dataset containing e-mails, it might be an good idea to use the following options:
``` -c --remove-email -j all ```

This will split and remove emails with a very basic regex. Also '-j all' will use all your cores and speed the whole process up.

**Review by zyronix — CHANGES_REQUESTED** [review]
See comment in pull request.

**Comment by bartbroere** [comment]
Okay, I have some time to start working on this one again. Thanks for the suggestions, and apologies that I didn't test it thoroughly enough yet.

TODO list:
- [ ] add logging about the number of hits
- [ ] document that glob patterns are allowed in module docstring
- [ ] document that glob patterns are allowed in README
- [ ] add a test specific to glob patterns

**Pull request merged**
